Repository BSData/warhammer-age-of-sigmar, pull requests merged in 2018-03, with the labels that each got.

#207 Battalion Validation for Flesh-eater Courts
  Death - Flesh-eater Courts.cat
Labels: UX enhancement

#211 Death Battalion Validation Update
  Death - Legions of Nagash.cat
Labels: Bug - text/rule/profile, Death, Resolution - fixed, UX enhancement

#225 Little Correction
  Order - Wanderers.cat
  Order - Wood Elves.cat
Labels: Bug - text/rule/profile
